Revert "Enable experimental_ppr - partial pre-rendering model"
This reverts commit 8c55bedb038e69b416bef3af4e6b76d658f216d8.

  Got build error:

    CanaryOnlyError: The experimental feature "experimental.ppr" can only
    be enabled when using the latest canary version of Next.js.

  Reverting change. No experimental_ppr for now.